### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by DutchPete** [artem-barmin/obsidian-block-drag-n-drop#4] opened 2022-04-16 14:35 UTC
I did not find it in the Community collection so I installed it via BRAT.
I enabled it, refreshed, quit/relaunched Obsidian, all to no avail.

I am on MacOS, Obs 0.14.6, installer version 0.14.5.

**Comment by kalmir** [comment] 2022-04-16 19:51
Same here, also MacOS, Obs 0.14.6.

**Comment by artem-barmin** [comment] 2022-04-16 22:32
Confirmed issue with BRAT. Now you can use "Manual installation" method.

**Comment by archizoo** [comment] 2022-04-17 01:01
Ditto here. Obs 0.14.5, Mac 12.3.1

**Comment by DutchPete** [comment] 2022-04-17 08:08
> Confirmed issue with BRAT on vanilla Obsidian setup. Look like unintended interaction with other installed plugins or themes. Will figure it out

It still does not work.

**Comment by artem-barmin** [comment] 2022-04-18 14:20
Try one more time with release "1.0.5"

**Comment by DutchPete** [comment] 2022-04-18 14:30
Now I get the 6 red dots only for bullet points. Furthermore, dragging those does not work.

**Comment by imeed166** [comment] 2022-04-18 15:02
> Now I get the 6 red dots only for bullet points.

Because for now, it supports only list items, other block types are in the roadmap (check readme).

**Comment by artem-barmin** [comment] 2022-04-18 15:09
Please record video - from the installing to trying to drag.

Also dragging is supported only for list items, and you can drop them only to list items(thats written in docs)

**Comment by DutchPete** [comment] 2022-04-18 15:14
OK, I missed the point about list items only, my apologies.

**Comment by artem-barmin** [comment] 2022-04-18 18:39
@DutchPete Can you try once more again and record video?

**Comment by archizoo** [comment] 2022-04-20 13:53
First, thanks very much for your efforts on our behalf. 

For me, the issue is that I just cannot "see" the plug-in. That is, I am on Obsidian 14.6 and the plugin just does not show up in the Community Plugins no matter what search terms I use. I'll keep looking, though, in subsequent updates. It seems as if you've developed a cool tool.

**Comment by artem-barmin** [comment] 2022-04-20 15:18
> First, thanks very much for your efforts on our behalf.
> 
> For me, the issue is that I just cannot "see" the plug-in. That is, I am on Obsidian 14.6 and the plugin just does not show up in the Community Plugins no matter what search terms I use. I'll keep looking, though, in subsequent updates. It seems as if you've developed a cool tool.

Unforunately it's not YET available in Community list. You can use [BRAT](https://github.com/TfTHacker/obsidian42-brat) to install it OR wait for some time until it will be accepted to official plugin list

I'm closing issue for now as it seems to work

**Closed by artem-barmin** 2022-04-20 15:18 UTC
